container-applications/JohnnyHash/JohnnyCipher/routes.py
from Ciphers.caesarcipher import CaesarCipher
from flask import Blueprint, jsonify, redirect, request, render_template, url_for
from globals import ds_client
from JohnnyCipher.utils import CaesarCipherBuilder, SubstitutionCipherBuilder

# Initialize Blueprint
johnnycipher = Blueprint(
    'johnnycipher',
    __name__,
    url_prefix='/johnnycipher',
    template_folder='email_templates',
    static_folder='static',
)


@johnnycipher.route('/caesar/<workout_id>', methods=['GET', 'POST'])
def caesar(workout_id):
    page_template = './cipher.jinja'

    key = ds_client.key('cybergym-workout', workout_id)
    workout = ds_client.get(key)

    # Only valid workouts can access
    if workout:
        if workout['type'] == 'johnnycipher':
            firstcipher = workout['container_info']['cipher_one']['cipher']
            secondcipher = workout['container_info']['cipher_two']['cipher']
            thirdcipher = workout['container_info']['cipher_three']['cipher']

            if request.method == 'GET':
                return render_template(
                    page_template,
                    workout_id=workout_id,
                    firstcipher=firstcipher,
                    secondcipher=secondcipher,
                    thirdcipher=thirdcipher,
                )
            elif request.method == 'POST':
                plaintext = request.get_json()
                # ['id'] helps determine which cipher is to be evaluated
                # app.logger.info('Checking cipher with id : %d' % int(plaintext['id']))
                validator = CaesarCipherBuilder(workout_id)
                data = validator.check_caesar(str(plaintext['cipher']), int(plaintext['id']))

                return jsonify({
                    'message1': data['cipher1']['cipher'],
                    'status1':  data['cipher1']['status'],
                    'message2': data['cipher2']['cipher'],
                    'status2':  data['cipher2']['status'],
                    'message3': data['cipher3']['cipher'],
                    'status3':  data['cipher3']['status'],
                })
        else:
            return redirect('/invalid')
    else:
        return redirect('/invalid')


@johnnycipher.route('/ajax_calculate_caesar/<workout_id>', methods=['POST'])
def ajax_calculate_caesar(workout_id):
    # Returns deciphered message
    encrypted_message = request.get_json()
    key = int(encrypted_message['key'])
    message = str(encrypted_message['ciphertext'])
    plaintext = CaesarCipher(message, offset=key).decoded

    return jsonify({'plaintext': plaintext})


@johnnycipher.route('/substitution/<workout_id>', methods=['GET', 'POST'])
def substitution(workout_id):
    page_template = './substitution.jinja'
    key = ds_client.key('cybergym-workout', workout_id)
    workout = ds_client.get(key)

    if workout:
        if workout['type'] == 'johnnycipher':
            if request.method == 'GET':
                cipher = workout['container_info']['sub_cipher']['cipher']
                status = workout['assessment']['questions'][3]['complete']

                return render_template(
                    page_template,
                    workout_id=workout_id,
                    sub_cipher=cipher,
                    status=status
                )
            elif request.method == 'POST':
                submission = request.get_json()
                validator = SubstitutionCipherBuilder(workout_id=workout_id)
                check_sub = validator.check_sub_cipher(submission['cipher'])
                cipher = check_sub['message']
                status = check_sub['status']

                return jsonify({'message': cipher, 'status': status})
        else:
            return redirect(url_for('johnnycipher.invalid'))
    else:
        return redirect(url_for('johnnycipher.invalid'))


@johnnycipher.route('/invalid', methods=['GET'])
def invalid():
    template = 'email_templates/invalid_workout.html'
    return render_template(template)

container-applications/JohnnyHash/JohnnyCipher/templates/cipher.jinja
{% extends "index.jinja" %}
{% block navblock %}
     <a href="{{ url_for('johnnycipher.caesar', workout_id=workout_id) }}">
        <i class="fa fa-key sidebar-icon"></i>
        <p class="sidebar-txt">Caesar Ciphers</p>
    </a>
    <a href="{{ url_for('johnnycipher.substitution', workout_id=workout_id) }}">
        <i class="fa fa-key sidebar-icon"></i>
        <p class="sidebar-txt">Substitution Cipher</p>
    </a>
{% endblock navblock %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('johnnycipher.static', filename='styles/johnnycipher-styles.css') }}">
{% endblock styles_block %}
{% block header_img %}
    <img class="banner-image"
         src="{{ url_for('.static', filename='img/sinister_alt_banner.jpg') }}"
         alt="shadowed figure">
{% endblock header_img %}
{% block background_img %}{% endblock background_img %}
{% block content %}
    <div class="inner-content-wrapper" id="cipherMain">
        <h1>Caesar Cipher</h1>
        <hr>
        <div class="inner-content-wrapper">
            <label class="cipher-label" for="ciphertext">Encrypted Message:</label>
            <input class="cipher-input" type="text" name="ciphertext" id="ciphertext" size="80">

            <label class="cipher-label" for="key">Key:</label>
            <input class="cipher-input" type="text" name="key" id="key" size="2" value="13">
            <button type="submit" class="btn" id="button_decrypt">Decrypt Message</button>
        </div>
        <div id="decrypted_results"></div>
        <br>
        <br>
        {# List of Ciphers they need to decipher: Needs to be submitted with Ajax #}
        <div class="cipher-div-wrapper" id="caesar-cipher-inputs">
            <div class="inner-content-wrapper" id="firstcipher">
                <p>{{ firstcipher }}</p>
                <label class="cipher-label" for="cipher1">Cipher 1:</label>
                <input type="text" size='80' name="cipher1" id="cipher1" class="cipher1 cipher-input" />
            </div>
            <div>
                <button class="btn" id="button_cipher1">Check Cipher</button>
            </div>
            <br><br>
            <div class="inner-content-wrapper" id="secondcipher">
                <p>{{ secondcipher }}</p>
                <label class="cipher-label" for="cipher2">Cipher 2:</label>
                <input type="text" size='80' name="cipher2" id="cipher2" class="cipher2 cipher-input"/>
            </div>
            <div>
                <button class="btn" id="button_cipher2">Check Cipher</button>
            </div>
            <br><br>
            <div class="inner-content-wrapper" id="thirdcipher">
                <p>{{ thirdcipher }}</p>
                <label class="cipher-label" for="cipher3">Cipher 3:</label>
                <input type="text" size='80' name="cipher3" id="cipher3" class="cipher3 cipher-input"/>
            </div>
            <div>
                <button class="btn" id="button_cipher3">Check Cipher</button>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js_block %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#button_decrypt').on('click', function() {
               const encrypted = $('#ciphertext').val();
               const key = String($('#key').val());
               $.ajax({
                  type : 'POST',
                  url : "{{ url_for('johnnycipher.ajax_calculate_caesar', workout_id=workout_id) }}",
                  data : JSON.stringify({ciphertext: encrypted, key: key}),
                  dataType : 'json',
                  contentType : 'application/json',
                  success : function(data) {
                      console.log('AJAX Success!');

                      display_caesar(data['plaintext']);
                  },
                   error : function(e) {
                      console.log('AJAX Error!');
                      console.log(e)
                   }
               });
            });
            function display_caesar(plaintext) {
                let results_div = $('#decrypted_results');

                results_div.html('');

                let html_string = 'Decrypted Message: ' + plaintext + '<br />';
                results_div.html(html_string);
            }
            $('#button_cipher1').on('click', function() {
               const message = $('#cipher1').val();
               $.ajax({
                  type : 'POST',
                  url : "{{ url_for('johnnycipher.caesar', workout_id=workout_id) }}",
                  data : JSON.stringify({cipher : message, id : 1}),
                  dataType : 'json',
                  contentType : 'application/json',
                  success : function(data) {
                      console.log('AJAX Success!');
                      display_cipher1_submission(data['status1'], data['message1']);
                  },
                   error : function(e) {
                      console.log('AJAX Error!');
                      console.log(e)
                   }
               });
            });
            function display_cipher1_submission(sub_status1, sub_message1) {
                let results_input = $('#cipher1');
                console.log(sub_status1)

                if (sub_status1 === true) {
                    results_input.html(sub_message1);
                    results_input.css('background-color', '#4CAF50');
                }
            }
            $('#button_cipher2').on('click', function() {
               const message = $('#cipher2').val();
               $.ajax({
                  type : 'POST',
                  url : "{{ url_for('johnnycipher.caesar', workout_id=workout_id) }}",
                  data : JSON.stringify({cipher : message, id : 2}),
                  dataType : 'json',
                  contentType : 'application/json',
                  success : function(data) {
                      console.log('AJAX Success!');
                      display_cipher2_submission(data['status2'], data['message2']);
                  },
                   error : function(e) {
                      console.log('AJAX Error!');
                      console.log(e)
                   }
               });
            });
            function display_cipher2_submission(sub_status2, sub_message2) {
                let results_input = $('#cipher2');

                if (sub_status2 === true) {
                    results_input.html(sub_message2);
                    results_input.css('background-color', '#4CAF50');
                }
            }
            $('#button_cipher3').on('click', function() {
               const message = $('#cipher3').val();
               $.ajax({
                  type : 'POST',
                  url : "{{ url_for('johnnycipher.caesar', workout_id=workout_id) }}",
                  data : JSON.stringify({cipher : message, id : 3}),
                  dataType : 'json',
                  contentType : 'application/json',
                  success : function(data) {
                      console.log('AJAX Success!');
                      display_cipher3_submission(data['status3'], data['message3']);
                  },
                   error : function(e) {
                      console.log('AJAX Error!');
                      console.log(e)
                   }
               });
            });
            function display_cipher3_submission(sub_status3, sub_message3) {
                let results_input = $('#cipher3');

                if (sub_status3 === true) {
                    results_input.html(sub_message3);
                    results_input.css('background-color', '#4CAF50');
                }
            }
        });
    </script>
{% endblock js_block %}

container-applications/JohnnyHash/JohnnyCipher/templates/index.jinja
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Johnny Hash{% endblock title %}</title>
    <link rel="icon" href="/static/img/spy.ico" type="image/png"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main-styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/modal-styles.css') }}">
    {% block styles_block %}{% endblock styles_block %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    {% block js_block %}{% endblock js_block %}
    {% block head_block %}{% endblock head_block %}
</head>
<body>
    <div class="sidebar">
        <img src="/static/img/sinister%20(2).jpg" style="width:100%" alt="shadowed figure">
        <a href="/{{ workout_id }}" >
            <i class="fa fa-home sidebar-icon"></i>
            <p class="sidebar-txt">HOME</p>
        </a>
        {% block navblock %}{% endblock navblock %}
    </div>
    <div class="main-content-wrapper">
        <header class="inner-content-wrapper banner-image" id="home">
            {% block header_img %}
                <img class="banner-image"
                     src="{{ url_for('.static', filename='img/sinister_alt_banner.jpg') }}"
                     alt="shadowed figure">
            {% endblock header_img %}
        </header>
    </div>
    <div class="main-content-wrapper">
         {% block content %}{% endblock content %}
    </div>
    <div class="footer-div">
        <p>&copy; Trojan Cyber Arena 2021</p>
    </div>
    </body>
</html>

container-applications/JohnnyHash/JohnnyCipher/templates/invalid_workout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="UA Little Rock Trojan Arena"/>
 	<meta name="author" content="UA Little Rock"/>
    <title>Cyber Gym - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
</head>
<style>
    body {
            font-family: 'Montserrat', sans-serif;
    }
    h3, h4 {
    		margin: 10px 0 30px 0;
    		letter-spacing: 2px;  /* 10px */
    		font-size: 20px;
    		color: #111; /* #111 */
	}
    .bg-1 {
            background: #6e2639; /* #2d2d30 */
            color: #a7a9ac; /*#bdbdbd */
	}
    .bg-1 h3 {
		    color: #a7a9ac; /* #fff */
	}
	.bg-1 p {
		    font-style: italic;
	}
    .form-ctn {
            width: 40%;
            margin-top: 10vh;
            -webkit-box-shadow: 0px 10px 13px -7px #000000, 15px 16px 8px -13px rgba(0,0,0,0.62);
            box-shadow: 0px 10px 13px -7px #000000, 15px 16px 8px -13px rgba(0,0,0,0.62);
            padding: 2%;
            background-color: white;
    }
    .btn-ctn {
            text-align: center;
            margin-top: 5vh;
    }
    .input-field {
            margin-top: 5vh;
    }
    .nav-tabs li a {
    		color: #777;
  	}
  	.navbar {
    		font-family: Montserrat, sans-serif;
    		background-color: #2d2d30;
    		border: 0;
    		font-size: 11px !important;
    		letter-spacing: 4px;
    		opacity: 0.9;
  	}
  	.navbar li a, .navbar .navbar-brand {
    		color: #d5d5d5 !important;
  	}
  	.navbar-nav li a:hover {
    		color: #fff !important;
  	}
  	.navbar-nav li.active a {
    		color: #fff !important;
    		background-color: #29292c !important;
  	}
  	.navbar-default .navbar-toggle {
    		border-color: transparent;
  	}

    .left {
        display: block;
        margin-left: 10vh;
        margin-top: 10vh;
        width: 20%;
        height: 25%;
    }
  	footer {
    		background-color: #6e2639; /* #2d2d30 */
    		color: #f5f5f5;
    		padding: 32px;
  	}
  	footer a {
    		color: #f5f5f5;
  	}
  	footer a:hover {
    		color: #777;
    		text-decoration: none;
  	}
    .loader {
      border: 5px solid #f3f3f3; /* Light grey */
      border-top: 5px solid #6e2639; /* BG color */
      border-radius: 50%;
      margin: auto;
      width: 40px;
      height: 40px;
      animation: spin 2s linear infinite;
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }

    ol.teams {
      list-style-type: none;
      counter-reset: elementcounter;
      padding-left: 0;
    }

    li.teams:before {
      content: "Team " counter(elementcounter) ": ";
      counter-increment: elementcounter;
      font-weight: bold;
    }

    td {
        text-align: center;
    }
</style>

<body id="homePage" data-spy="scroll" data-target=".navbar" data-offset="50" class="bg-1">
    <div id="workout-form" class='container-fluid form-ctn'>
        <div class="center">
            <img src="/static/img/CyberGymLogo_small.png" alt="UA Little Rock Cyber Gym Logo"/>
            {% block content %}{% endblock %}
            <p>You have reached this page by error. Please verify you are meant to go here.</p>
        </div>
    </div>

<footer class="text-center">
	<br><br>
	<p>UA Little Rock Emerging Analytics Center</p>
    <p>This material is based upon work supported by the National Science Foundation under Grant No. 1623628</p>
</footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script>
            $(document).ready(function(){
                // Initialize Tooltip
                $('[data-toggle="tooltip"]').tooltip();

                // Add smooth scrolling to all links in navbar + footer link
                $(".navbar a, footer a[href='#homePage']").on('click', function(event) {
                    // Make sure this.hash has a value before overriding default behavior
                    if (this.hash !== "") {
                        // Prevent default anchor click behavior
                        event.preventDefault();
                            var hash = this.hash;

                            // Using jQuery's animate() method to add smooth page scroll
                            // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                            $('html, body').animate({
                            scrollTop: $(hash).offset().top
                            }, 900, function(){

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                        });
                    }
                });
            });
    </script>
</body>
</html>

container-applications/JohnnyHash/JohnnyCipher/templates/substitution.jinja
{% extends "index.jinja" %}
{% block navblock %}
     <a href="{{ url_for('johnnycipher.caesar', workout_id=workout_id) }}">
        <i class="fa fa-key sidebar-icon"></i>
        <p class="sidebar-txt">Caesar Ciphers</p>
    </a>
    <a href="{{ url_for('johnnycipher.substitution', workout_id=workout_id) }}">
        <i class="fa fa-key sidebar-icon"></i>
        <p class="sidebar-txt">Substitution Cipher</p>
    </a>
{% endblock navblock %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('johnnycipher.static', filename='styles/johnnycipher-styles.css') }}">
{% endblock styles_block %}
{% block header_img %}
    <img class="banner-image"
         src="{{ url_for('.static', filename='img/sinister_alt_banner.jpg') }}"
         alt="shadowed figure">
{% endblock header_img %}
{% block background_img %}{% endblock background_img %}
{% block content %}
{# <body style="text-align:center;margin:60px"> #}
<div class="inner-content-wrapper" style="text-align: center" id="main">
    <h1>Substitution Cipher</h1>
    <br>
    {# List of Ciphers they need to decipher: Needs to be submitted with Ajax #}
    <div class="inner-content-wrapper" id="caesar-cipher-inputs">
        <div class="inner-content-wrapper" id="firstcipher">
            <p>Cipher: {{ sub_cipher }}</p>
            <label class="cipher-label" for="cipher1">Cleartext:</label>
            <input type="text" size='80' name="cipher1" id="cipher1" class="cipher1 cipher-input" />
        </div>
        <div>
            <button class="btn" id="button_cipher1">Check Message</button>
        </div>
        <br><br>
    </div>
</div>
{#  </body> #}
{% endblock content %}
{% block js_block %}
     <script type="text/javascript">
        $(document).ready(function() {
            $('#button_cipher1').on('click', function () {
                const message = $('#cipher1').val();
                $.ajax({
                    type: 'POST',
                    url: "{{ url_for('johnnycipher.substitution', workout_id=workout_id) }}",
                    data: JSON.stringify({cipher: message}),
                    dataType: 'json',
                    contentType: 'application/json',
                    success: function (data) {
                        console.log('AJAX Success!');
                        display_cipher_submission(data['status'], data['message']);
                    },
                    error: function (e) {
                        console.log('AJAX Error!');
                        console.log(e)
                    }
                });
            });

            function display_cipher_submission(sub_status, sub_message) {
                let results_input = $('#cipher1');
                if (sub_status === true) {
                    results_input.html(sub_message);
                    results_input.css('background-color', '#4CAF50');
                }
            }
        });
     </script>
{% endblock js_block %}