container-applications/JohnnyHash/GenCyber1/routes.py
from flask import Blueprint, jsonify, redirect, request, render_template
from globals import ds_client
from GenCyber1.utils import get_arena_sub_cipher

# Initialize Blueprint
johnnyGenCipher = Blueprint(
    'johnnyGenCipher',
    __name__,
    url_prefix='/johnnyGenCipher',
    template_folder='email_templates/johnnyGenCipher',
    static_folder='static',
)


@johnnyGenCipher.route('/substitution/<workout_id>', methods=['GET'])
def substitution(workout_id):
    page_template = 'johnnyGenCipher/substitution.jinja'
    key = ds_client.key('cybergym-workout', workout_id)
    workout = ds_client.get(key)

    if workout:
        if workout['type'] == 'GenCyber Arena Level 1':
            if request.method == 'GET':
                cipher = get_arena_sub_cipher()

                return render_template(
                    page_template,
                    workout_id=workout_id,
                    sub_cipher=cipher,
                )
        else:
            return redirect('/invalid')
    else:
        return redirect('/invalid')


@johnnyGenCipher.route('/invalid', methods=['GET'])
def invalid():
    template = 'johnnyGenCipher/invalid_workout.html'
    return render_template(template)

container-applications/JohnnyHash/GenCyber1/templates/index.jinja
<!--Hold Basic page functionality -->
<!doctype html>
<html lang="en-US">
    <head>
       <title>{% block title %}Johnny Hash{% endblock title %}</title>
        <link rel="icon" href="/static/img/spy.ico" type="image/png"/>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
            .w3-row-padding img {margin-bottom: 12px;}
            {#  Set the width of the sidebar to 120px#}
            .w3-sidebar {width: 120px;background: #222;}
            {# Add a left margin to the "page content" that matches the width of the sidebar (120px) #}
            #main {margin-left: 120px;}
            {#  Remove margins from "page content" on small screens #}
            @media only screen and (max-width: 600px) { #main {margin-left: 0} }
        </style>
        {% block styles_block %}{% endblock styles_block %}
        {% block head_block %}{% endblock head_block %}
        {#
        This block can be overwritten by child templates to add page-specific CSS
        #}
    </head>
    <body class="w3-black">
        <div>
        <!-- Icon Bar (Sidebar - hidden on small screens) -->
        <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
          <!-- Avatar image in top left corner -->
          <img src="/static/img/sinister%20(2).jpg" style="width:100%" alt="a thing" class="w3-border-blue-gray">

          <a href="/{{ workout_id }}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
            <i class="fa fa-home w3-xxlarge"></i>
            <p>HOME</p>
          </a>
          <a href="{{ url_for('johnnyGenCipher.substitution', workout_id=workout_id) }}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
            <i class="fa fa-key w3-xxlarge"></i>
            <p>A Crypto Challenge</p>
          </a>
          {% block navblock %} {% endblock navblock %}
        </nav>
        </div>

        {% block picture %}
            <style>
                img {
                    height: auto;
                    width: 80%;
                }
            </style>
            <div class="w3-padding-large" id="main">
              <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
               <img src="/static/img/sinister_alt_banner.jpg" alt="a bigger thing" class="w3-image">
              </header>
            </div>
        {% endblock picture %}
        {% block content %}{# Page content goes here... #}{% endblock content %}

        <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">
          <p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
        </footer>

        <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        {% block js_block %}{% endblock js_block %}
    </body>
</html>

container-applications/JohnnyHash/GenCyber1/templates/invalid_workout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="UA Little Rock Trojan Arena"/>
 	<meta name="author" content="UA Little Rock"/>
    <title>Cyber Gym - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
</head>
<style>
    body {
            font-family: 'Montserrat', sans-serif;
    }
    h3, h4 {
    		margin: 10px 0 30px 0;
    		letter-spacing: 2px;  /* 10px */
    		font-size: 20px;
    		color: #111; /* #111 */
	}
    .bg-1 {
            background: #6e2639; /* #2d2d30 */
            color: #a7a9ac; /*#bdbdbd */
	}
    .bg-1 h3 {
		    color: #a7a9ac; /* #fff */
	}
	.bg-1 p {
		    font-style: italic;
	}
    .form-ctn {
            width: 40%;
            margin-top: 10vh;
            -webkit-box-shadow: 0px 10px 13px -7px #000000, 15px 16px 8px -13px rgba(0,0,0,0.62);
            box-shadow: 0px 10px 13px -7px #000000, 15px 16px 8px -13px rgba(0,0,0,0.62);
            padding: 2%;
            background-color: white;
    }
    .btn-ctn {
            text-align: center;
            margin-top: 5vh;
    }
    .input-field {
            margin-top: 5vh;
    }
    .nav-tabs li a {
    		color: #777;
  	}
  	.navbar {
    		font-family: Montserrat, sans-serif;
    		background-color: #2d2d30;
    		border: 0;
    		font-size: 11px !important;
    		letter-spacing: 4px;
    		opacity: 0.9;
  	}
  	.navbar li a, .navbar .navbar-brand {
    		color: #d5d5d5 !important;
  	}
  	.navbar-nav li a:hover {
    		color: #fff !important;
  	}
  	.navbar-nav li.active a {
    		color: #fff !important;
    		background-color: #29292c !important;
  	}
  	.navbar-default .navbar-toggle {
    		border-color: transparent;
  	}

    .left {
        display: block;
        margin-left: 10vh;
        margin-top: 10vh;
        width: 20%;
        height: 25%;
    }
  	footer {
    		background-color: #6e2639; /* #2d2d30 */
    		color: #f5f5f5;
    		padding: 32px;
  	}
  	footer a {
    		color: #f5f5f5;
  	}
  	footer a:hover {
    		color: #777;
    		text-decoration: none;
  	}
    .loader {
      border: 5px solid #f3f3f3; /* Light grey */
      border-top: 5px solid #6e2639; /* BG color */
      border-radius: 50%;
      margin: auto;
      width: 40px;
      height: 40px;
      animation: spin 2s linear infinite;
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }

    ol.teams {
      list-style-type: none;
      counter-reset: elementcounter;
      padding-left: 0;
    }

    li.teams:before {
      content: "Team " counter(elementcounter) ": ";
      counter-increment: elementcounter;
      font-weight: bold;
    }

    td {
        text-align: center;
    }
</style>

<body id="homePage" data-spy="scroll" data-target=".navbar" data-offset="50" class="bg-1">
    <div id="workout-form" class='container-fluid form-ctn'>
        <div class="center">
            <img src="/static/img/CyberGymLogo_small.png" alt="UA Little Rock Cyber Gym Logo"/>
            {% block content %}{% endblock %}
            <p>You have reached this page by error. Please verify you are meant to go here.</p>
        </div>
    </div>

<footer class="text-center">
	<br><br>
	<p>UA Little Rock Emerging Analytics Center</p>
    <p>This material is based upon work supported by the National Science Foundation under Grant No. 1623628</p>
</footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script>
            $(document).ready(function(){
                // Initialize Tooltip
                $('[data-toggle="tooltip"]').tooltip();

                // Add smooth scrolling to all links in navbar + footer link
                $(".navbar a, footer a[href='#homePage']").on('click', function(event) {
                    // Make sure this.hash has a value before overriding default behavior
                    if (this.hash !== "") {
                        // Prevent default anchor click behavior
                        event.preventDefault();
                            var hash = this.hash;

                            // Using jQuery's animate() method to add smooth page scroll
                            // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                            $('html, body').animate({
                            scrollTop: $(hash).offset().top
                            }, 900, function(){

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                        });
                    }
                });
            });
    </script>
</body>
</html>

container-applications/JohnnyHash/GenCyber1/templates/substitution.jinja
{% extends "johnnyGenCipher/index.jinja" %}
{% block navblock %}{% endblock navblock %}
{% block background_img %}{% endblock background_img %}
{% block styles_block %}
    <style>
        #main {
            text-align: center;
            padding-left: 50px;
        }
        #cipher-div {
            font-size: 22px;
            font-style: normal;
            font-weight: bold;
            text-align: left;
            margin-left: 100px;
            margin-right: 0px;
        }
        #subdescription {
            font-size: 20px;
            font-weight: normal;
            width: 80%;
         }
        .subciphertext {
            width: 80%;
            padding-left: 20px;
            margin-left: 20px;
            font-size: 20px;
            font-weight: normal;
        }
    </style>
{% endblock styles_block %}
{% block content %}
{# <body style="text-align:center;margin:60px"> #}
<div id="main">
    <h2>A Crypto Challenge</h2>
    <br>
    {# List of Ciphers they need to decipher: Needs to be submitted with Ajax #}
    <div class="w3-section" id="caesar-cipher-inputs">
        <div class="w3-section" id="cipher-div">
            <p id="subdescription">While you were taking a walk outside, you heard a commotion and turned to see a hooded stranger sprint
                pass. As he continued on, a piece of paper with a strange note dropped out of his pocket. You pick it up
                and this is what you see. Can you decode the message?</p>
            <p>Ciphertext:</p>
            <p class="subciphertext">{{ sub_cipher }}</p>
            <p style="font-size: 14px;">Hint: <br>I wonder if there is a relation to letter frequency in English alphabet?</p>
        </div>
    </div>
</div>
{#  </body> #}
{% endblock content %}
{% block js_block %}
{% endblock js_block %}