container-applications/IoT/GenCyberIoT/routes.py
import json
from flask import Blueprint, flash, jsonify, redirect, render_template, request, make_response, url_for
from google.api_core.exceptions import NotFound
from app_utilities.gcp.iot_manager import IotManager
from app_utilities.gcp.cloud_env import CloudEnv

# Blueprint Configuration
iot_bp = Blueprint(
    'iot_bp', __name__,
    url_prefix='/iot',
    template_folder='templates',
    static_folder='static'
)

env = CloudEnv()


@iot_bp.route('/', methods=['GET', 'POST'])
def setup():
    page_template = './iot_setup.jinja'
    if request.method == 'POST':
        print(request.data)
        resp = json.loads(request.data)
        device_id = resp['device_id']
        iot_manager = IotManager(device_id=device_id)
        if check_device := iot_manager.check_device():
            print(f'Received object {resp}')
            return jsonify({'url': url_for('iot_bp.index', device_id=device_id)})
        message = jsonify({'error_msg': f'Unrecognized device with ID: {device_id}'})
        return make_response(message, 400)
    return render_template(page_template)


@iot_bp.route('/faq', methods=['GET'])
def faq():
    page_template = './faq.jinja'
    return render_template(page_template, project=env.project)


@iot_bp.route('/commands/<device_id>', methods=['GET'])
def index(device_id):
    page_template = './iot-v2.html'
    iot_mgr = IotManager(device_id=device_id)

    # Pass level_1 flag back in override var to unlock level_2 of the challenge
    override = None
    # Supported Commands; Passed through template to generate buttons
    commands = {
        # banned_commands = ['green']
        'functions': ['humidity', 'pressure', 'temp'],
        'colors': ['red', 'orange', 'yellow', 'purple', 'blue', 'teal']
    }

    iot_data = None
    if (iot_data := iot_mgr.get()) and iot_data is not None:
        print(f'database query returned: {iot_data}')
        json_data = json.dumps(iot_data['sensor_data'])
        return render_template(
            page_template,
            device_id=device_id,
            commands=commands,
            override=override,
            iot_data=dict(iot_data),
            iot_json=json.dumps(iot_data['sensor_data'])
        )
    flash("Couldn\'t connect to device. Is it online?")
    return redirect(url_for('iot_bp.setup'))


@iot_bp.route('/commands/<device_id>/submit', methods=['POST'])
def submit(device_id):
    if request.method == 'POST':
        iot_mgr = IotManager(device_id)
        resp = json.loads(request.data)
        if command := resp.get('command'):
            success, data = iot_mgr.msg(command, device_type=4553232)
            if success:
                return jsonify(success=True)
            else:
                if data[1] == NotFound:
                    flash(f'Device {device_id} responded with 404. Ensure the device is properly connected.',
                          'alert-warning')
                return jsonify(error=data[1])
        return jsonify({'resp': 400})
    else:
        return jsonify({'resp': 404})

container-applications/IoT/GenCyberIoT/templates/base.jinja
<!doctype html>
<html lang="en-US">
<head>
{% block header_block %}
    <meta charset="utf-8">
    <title>{% block title_block %}{% endblock title_block %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ url_for('.static', filename='imgs/iot-icon_2.ico') }}" id="nav-ico">
    <link rel="stylesheet" href="{{ url_for('.static', filename='css/iot-styles.css') }}">
    {% block styles_block %}{% endblock styles_block %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    {% block js_block %} {% endblock js_block %}
{% endblock header_block %}
</head>
<body style="background-color: inherit;">
    <nav class="iot-navbar">
        <img src="{{ url_for('.static', filename='imgs/iot-pc.png') }}" id="nav-img" title="open-pc">
        {% block nav_block %}{% endblock nav_block %}
    </nav>
    <div class="html-container">
        <!-- Body Content -->
        <div class="body-container center-content">
            {% block content_block %}{% endblock content_block %}
        </div>
        <div class="iot-footer">
            <p class="iot-footer">{% block footer_block %}{% endblock footer_block %}</p>
            <p class="iot-footer">
                &copy; Trojan Cyber Arena
            </p>
        </div>
    </div>
</body>
</html>

container-applications/IoT/GenCyberIoT/templates/display_code.html
{% macro display_code(data) -%}
    {% for obj in data %}
        {{ data[obj] }}
    {% endfor %}
{%- endmacro %}
{% macro display_patients(patients) %}
    {% for patient in patients %}
        {{- display_code(patients[patient]) -}}
    {% endfor %}
{% endmacro %}
{% macro display_car(car) %}
    {% for d in car %}
        '{{ d }}': {{ car[d] }}
    {% endfor %}
{% endmacro %}
{% macro render(data) %}
    <div class="code-block">
        {% for obj in data %}
            '{{ obj }}': {{ data[obj] }},
        {% endfor %}
    </div>
{% endmacro %}

container-applications/IoT/GenCyberIoT/templates/faq.jinja
{% extends 'base.jinja' %}
{% block title_block %}{% endblock title_block %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('.static', filename='css/faq-styles.css') }}">
{% endblock styles_block %}
{% block js_block %}

{% endblock js_block %}
{% block nav_block %}{% endblock nav_block %}
{% block content_block %}
    <div class="faqDivWrapper">
        <h1 id="faq-h1">FAQ</h1>
        <button type="button" class="faqDivBtn">My device is turned on, but I can't see my display</button>
        <div id="faq-1" class="faqContentDiv center-content">
            <p>
                A common mistake is to plug the HDMI cable into a computer or laptop. This won't work as most computers are
                only setup to transmit and not receive video signal.
            </p>
            <h3>Solution: </h3>
            <p>
                Make sure that your micro HDMI to HDMI cable is firmly seated in the Raspberry Pi and that the HDMI end is
                connected to a monitor or TV with an HDMI port. If at this point, there is still no signal, verify that your
                monitor or TV is listening on the correct channel.
            </p>
        </div>
        <button type="button" class="faqDivBtn">My device doesn't detect my keyboard</button>
        <div id="faq-2" class="faqContentDiv">
            <p>
                Order matters! When plugging in all the cables to your device, make sure that you plug in your peripherals
                first before plugging in the power cable.
            </p>
            <h3>Solution:</h3>
            <p>First make sure that you plugged your micro USB to USB adapter in the correct port. The device input port is
                the leftmost micro USB port. The rightmost micro USB port is reserved for power only.
                <br>
                Once you've determined that the cable is inserted into the correct port, simply restart the device.
            </p>
        </div>
        <button type="button" class="faqDivBtn">Can't see keyboard input when typing the login password</button>
        <div id="faq-3" class="faqContentDiv">
            <p>This is actually considered a security feature of Unix systems. During a login event, password input
            is not displayed to the screen to help prevent character length based password attacks.</p>
            <h3>Solution: </h3>
            <p>When you are prompted for the password, enter it as normal and hit enter. If you entered the password in
                correctly, you'll logged in.
            </p>
        </div>
        <button type="button" class="faqDivBtn">Connected my device to the network, but I'm unable to send commands</button>
        <div id="faq-4" class="faqContentDiv">
            <p>Usually this means that the device was not able to establish a successful connection to the Cloud.</p>
            Upon a successful connection, you should see a rotating blue and yellow image on your SenseHat display.
            <h3>Solution: </h3>
            <ui>
                <li>
                    Open <b>/usr/src/cyberarena-dev/config.yaml</b> with an editor of choice (nano or vim) and
                    verify that the <i>gcp</i> block matches your environment. Project value should be
                    <b>{{ project }}</b> and device_id should match what is on the bottom of your device.
                    <br><br><b>NOTE:</b> If you make any changes to this file, make sure to restart the device in order
                    for your changes to take effect.<br><br>
                </li>
                <li>
                    If the above suggestion doesn't help, it is possible that your local firewall is blocking traffic.
                    Make sure that port 8883 is open to traffic to <b>mqtt.googleapis.com</b>
                </li>
            </ui>
        </div>
        <button type="button" class="faqDivBtn">SenseHat display never turns off</button>
        <div id="faq-5" class="faqContentDiv">
            <p>This is usually a result of a bad connection from the SenseHat display to the Raspberry Pi. If this is
            the case, the Raspberry Pi can't properly detect what is connected to the GPIO pins and as a result isn't
            able to control any of the LEDs in the display</p>
            <h3>Solution: </h3>
            <p>Try reseating the SenseHat display by removing it and carefully pushing it back down on the GPIO pins. It
            should slide on smoothly but firmly. Be careful not to twist or bend any of the pins or this could effect
            any future connections</p>
        </div>
        {# <button type="button" class="faqDivBtn"></button>
        {#        <div id="faq-*" class="faqContentDiv">
        {#            <p></p>
        {#            <h3>Solution: </h3>
        {#            <p></p>
        {#        </div>
         #}
    </div>
    <script type="text/javascript">
        var coll = document.getElementsByClassName("faqDivBtn");
            var i;

            for (i = 0; i < coll.length; i++) {
              coll[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                console.log(content.id);
                if (content.style.display === "block") {
                  content.style.display = "none";
                } else {
                  content.style.display = "block";
                }
              });
            }
    </script>
{% endblock content_block %}
{% block footer_block %}
    <a href="{{ url_for('iot_bp.setup') }}">Back to Setup page &crarr;</a>
{% endblock footer_block %}

container-applications/IoT/GenCyberIoT/templates/iot-v2.html
{% extends 'base.jinja' %}
{% import 'car.jinja' as car %}
{% import 'quick_commands.html' as quick_commands %}
{% import 'display_code.html' as code_block %}
{% block title_block %}IoT Command and Control{% endblock title_block %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('iot_bp.static', filename='css/animations.css') }}">
    <link rel="stylesheet" href="{{ url_for('iot_bp.static', filename='css/iot-styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('iot_bp.static', filename='css/dashboard.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock styles_block %}
{% block js_block %}
    <script src="{{ url_for('iot_bp.static', filename='js/commands.js') }}" type="text/javascript"></script>
{% endblock js_block %}
{% block nav_block %}
    <h1>IoT Command and Control</h1>
    <div class="navbar-top">
        <ul class="navbar-list">
            <li>
                <button class="tab-btns tabLinks active" id="command-home-tab"
                        onclick="openTab(event, 'quick-commands')">Quick Commands</button>
            </li>
            <li>
                <button class="tab-btns tabLinks" onclick="openTab(event, 'car-dashboard')">Car Control</button>
            </li>
            <li>
                <button class="tab-btns tabLinks" onclick="openTab(event, 'raw-data')">Raw Data</button>
            </li>
        </ul>
    </div>
{% endblock nav_block %}
{% block content_block %}
    <script>
        function getDeviceID(){
            return '{{ device_id }}';
        }
    </script>
    <div class="tabContent" id="quick-commands" style="display: block;">
        {{ quick_commands.render(iot_data, iot_json, commands, "%s" % url_for('iot_bp.submit', device_id=device_id) , tab_idx) }}
    </div>
    <div class="tabContent" id="car-dashboard">
        {{ car.render(iot_data, iot_json, "%s" % url_for('iot_bp.submit', device_id=device_id), tab_idx) }}
    </div>
    <div class="tabContent" id="raw-data">
        {{ code_block.render(iot_data) }}
    </div>
{% endblock content_block %}

container-applications/IoT/GenCyberIoT/templates/iot.jinja
{% extends 'base.jinja' %}
{% block title_block %}IoT Command and Control{% endblock title_block %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('iot_bp.static', filename='css/animations.css') }}">
    <link rel="stylesheet" href="{{ url_for('iot_bp.static', filename='css/iot-styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock styles_block %}
{% block js_block %}
    <script src="{{ url_for('iot_bp.static', filename='js/commands.js') }}" type="text/javascript"></script>
    <script src="{{url_for('iot_bp.static', filename='js/self-driving.js')}}" type="text/javascript"></script>
{% endblock js_block %}
{% block nav_block %}
    <h1>IoT Command and Control</h1>
{% endblock nav_block %}
{% block content_block %}
    <div class="body-grid">
        <div class="tab">
            <button class="tablinks" id="command-home-tab" onclick="openTab(event, 'quick-commands')">Quick Commands</button>
            <button class="tablinks" onclick="openTab(event, 'self-driving')">Self Driving Controls</button>
        </div>
        <div class="command-results-grid">
            <div class="command-result-error">
                <p id="command-result-error"><p>
            </div>
            {% if iot_data %}
                <p>{{ iot_data.sensor_data }}</p>

                {% if iot_data.sensor_data.flag %}
                    <input class="modal-checkbox-cb" id="modal-checkbox-cb" type="checkbox" />
                    <div class="modal-popup">
                      <span class="modal-message">
                          {{ iot_data['sensor_data']['flag'] }}
                      </span>
                      <label for="modal-checkbox-cb" class="modal-close-cb"><a></a>x</label>
                    </div>
                {% endif %}
            {% endif %}
        </div>

        <div id="quick-commands" class="command-grid tabContent">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert {{category}}" role="alert"> {{ message }} </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <h1>Quick IoT Commands</h1>
            <h2>Data Functions </h2>
            {% for command in commands.functions %}
                <button class="iot-commands" id="{{ command }}"
                        onclick="send_command('{{ command }}', '{{ device_id }}', '{{ url_for('iot_bp.submit', device_id=device_id) }}');">
                    {{ command }}
                </button>
            {% endfor %}
            <h2>Display Colors </h2>
            {% for color in commands.colors %}
                <button class="iot-commands" id="{{ color }}"
                        onclick="send_command('{{ color }}', '{{ device_id }}', '{{ url_for('iot_bp.submit', device_id=device_id) }}');">
                    {{ color }}
                </button>
            {% endfor %}
            <!--Note: Why is this command here? Kind of redundant, no?
            <button class="iot-commands" id="green"
                        onclick="send_command('green', '{{ device_id }}', '{{ url_for('iot_bp.submit', device_id=device_id) }}');">
                    green
            </button>-->
        </div>
        <div class="tabContent command-grid" id="self-driving">
            <div style="display: flex;">
                <div id="self-driving-dashboard">
                    <div id="accelerometer_wrapper" style="height:400px;width:400px;margin:auto;">
                        <h2 style="text-align:center;">Speedometer</h2>
                        <svg id="speedometer" style="width:100%;height: 100%; transform: rotateX(180deg);z-index:-1">
                            <circle r="150" cx="50%" cy="50%" fill="none" stroke="blue" stroke-dasharray="471, 943" stroke-width="5px"></circle>
                            <circle r="150" cx="50%" cy="50%" fill="none" stroke="yellow" stroke-dasharray="236, 943" stroke-width="7px"></circle>
                            <circle r="150" cx="50%" cy="50%" fill="none" stroke="red" stroke-dasharray="70, 943" stroke-width="10px"></circle>
                            <path style="transform-origin: right center;transform-box: fill-box" id="indicator" d="M50 200 L200 205 L200 195 Z" />
                            <text x="45%" y="-125" style="transform: rotateX(180deg); font: bold 4em monospace;" id="speed-display">0 mph</text>
                        </svg>
                    </div>
                    <div id="accelerometer_controls" style="display: flex; width:400px; margin:auto; justify-content: space-around;">
                        <button class="iot-commands" id="brake_control" style="z-index:1">
                            Brake
                        </button>
                        <button class="iot-commands" id="gas_control" style="z-index:1">
                            Accelerate
                        </button><br>  
                    </div>
                    <!--Use these buttons to control the speed of the device. Be careful, if the speed exceeds 100mph, who knows what might happen...-->
                </div>
                <div id="thermometer_wrapper" style="height: 200px; width: 300px;">
                    <h2 style="text-align:center;">Temperature</h2>

                    <svg id="thermometer" style="height:100%; padding-top: 2em;">
                        <defs>
                            <linearGradient id="heat_grad" x1="0%" y1="0%" x2="0%" y2="100%">
                                <stop offset="0%" style="stop-color:rgb(255, 0, 0); stop-opacity: 1" />
                                <stop offset="100%" style="stop-color: rgb(60, 150, 252); stop-opacity: 1" />
                            </linearGradient>
                        </defs>
                        <circle r="18" cx="150px" cy="135px" fill="rgb(60, 150, 252)"></circle>
                        <rect x="140" y="0" width="20" height="125" rx="5" ry="5" fill="url(#heat_grad)"/>
                        {% if iot_data %}
                        <rect x="140" y="0" width="20" height="{{ 125 - iot_data.sensor_data.temp[:-1] |float }}" stroke-dasharray="50" rx="5" ry="5" fill="grey"/>
                        <text x="175" y="125" style="font: bold 2em monospace">{{iot_data.sensor_data.temp}}</text>
                        {% endif %}
                    </svg>
                </div>
            </div>
        </div>
        <div class="info-grid">
            <h2>Device ID: </h2> <p id="device_id">{{ device_id }}</p>
            {% if iot_data %}
            <h2>IP Address: </h2> <p>{{ iot_data.ip }}</p>
            <h2>Load: </h2> <p>{{ iot_data.memory }}%</p>
            <h2>Storage: </h2> <p>{{ iot_data.storage }}%</p>
            {% endif %}
        </div>
    </div>

{% endblock content_block %}

container-applications/IoT/GenCyberIoT/templates/iot_setup.jinja
{% extends 'base.jinja' %}
{% block styles_block %}
    <link rel="stylesheet" href="{{ url_for('.static', filename='css/iot-styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('.static', filename='css/animations.css') }}">
{% endblock styles_block %}
{% block js_block %}
    <script src="{{ url_for('iot_bp.static', filename='js/animations.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('iot_bp.static', filename='js/commands.js') }}" type="text/javascript"></script>
{% endblock js_block %}
{% block title_block %}Iot Device Setup{% endblock title_block %}
{% block nav_block %}<h1>IoT Device Setup</h1>{% endblock nav_block %}
{% block content_block %}
    <div class="blue-div-wrapper center-content" id="blue-div-wrapper">
        <div class="iot-setup-container center-content" id="iot-setup-container">
            <div class="error-msg" id="error-msg-div">
                <p id="error-msg-p">
                {% with messages = get_flashed_messages() %}
                  {% if messages %}
                    {% for message in messages %}
                      {{ message }}
                    {% endfor %}
                  {% endif %}
                {% endwith %}
                {% if error %}
                    {{ error }}
                {% endif %}
                </p>
            </div>
            <div id="animated-text-div"></div>
            <input type="text" name="iot-device-input" id="iot-device-input" placeholder="Enter your Device ID" required/>
            <button type="submit" class="iot-commands" id="iot-device-input-btn"
                onclick="sendDeviceID($('#iot-device-input').val(),
                '{{ url_for('iot_bp.setup') }}', 'iot-setup-container');">Connect!
            </button>
        </div>
    </div>
{% endblock content_block %}
{% block footer_block %}
    Trouble Connecting Your Device? <a href="{{ url_for('iot_bp.faq') }}">Check out our FAQ.</a>
{% endblock footer_block %}

container-applications/IoT/GenCyberIoT/templates/quick_commands.html
{% macro render(iot_data, iot_json, commands, url, tab_idx) %}
<div class="body-grid">
    <div class="command-results-grid">
        <div class="command-result-error">
            <p id="command-result-error{{ tab_idx }}"><p>
        </div>
        {% if iot_data %}
            <p>{{ iot_json }}</p>
            {% if iot_data.flag %}
                <input class="modal-checkbox-cb" id="modal-checkbox-cb{{ tab_idx }}" type="checkbox" />
                <div class="modal-popup">
                  <span class="modal-message">
                      {{ iot_data['flag'] }}
                  </span>
                  <label for="modal-checkbox-cb{{ tab_idx }}" class="modal-close-cb"><a></a>x</label>
                </div>
            {% endif %}
        {% endif %}
    </div>
    <div id="quick-commands" class="command-grid">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert {{category}}" role="alert"> {{ message }} </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h1>Quick IoT Commands</h1>
        <h2>Data Functions </h2>
        {% for command in commands.functions %}
            <button class="iot-commands" id="{{ command }}"
                    onclick="send_command('{{ command }}', '{{ device_id }}', '{{ url }}', {{ tab_idx }});">
                {{ command }}
            </button>
        {% endfor %}
        <h2>Display Colors </h2>
        {% for color in commands.colors %}
            <button class="iot-commands" id="{{ color }}"
                    onclick="send_command('{{ color }}', '{{ device_id }}', '{{ url }}', {{ tab_idx }});">
                {{ color }}
            </button>
        {% endfor %}
        <!--Note: Why is this command here? Kind of redundant, no?
        <button class="iot-commands" id="green"
                    onclick="send_command('green', '{{ device_id }}', '{{ url }}', {{ tab_idx }});">
                green
        </button>-->
    </div>
    <div class="info-grid">
        <h2>Device ID: </h2> <p id="device_id{{ tab_idx }}">{{ device_id }}</p>
        {% if iot_data %}
            <h2>IP Address: </h2> <p>{{ iot_data.ip }}</p>
            <h2>Load: </h2> <p>{{ iot_data.memory }}%</p>
            <h2>Storage: </h2> <p>{{ iot_data.storage }}%</p>
        {% endif %}
    </div>
</div>
{% endmacro %}